name: Deploy to ECS Canary
run-name: ${{ github.actor }} start workflow

on:
  push:
    branches:
      - main

jobs:
  create-docker-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Iniciar sesión en AWS ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
    
      - name: Crear, etiquetar y enviar imágen a AWS ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: test-nginx
          IMAGE_TAG: 2
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          echo "ECR_REGISTRY=$ECR_REGISTRY" >> $GITHUB_ENV
          echo "ECR_REPOSITORY=$ECR_REPOSITORY" >> $GITHUB_ENV
          echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV

      - name: Actualizar definición de tarea
        run: |
          IMAGE_URI="${{ env.ECR_REGISTRY }}/${{ env.ECR_REPOSITORY }}:${{ env.IMAGE_TAG }}"
          jq '.containerDefinitions[0].image = "'$IMAGE_URI'"' task-definition.json > updated-task-definition.json
        
      
      - name: Registrar definición de tarea
        run: |
          aws ecs register-task-definition --cli-input-json file://updated-task-definition.json

      - name: Obtener ARN de la definición de tarea
        id: get-task-def-arn
        run: |
          TASK_DEF_ARN=$(aws ecs list-task-definitions --family-prefix test-ecs-taks --sort DESC --max-items 1 --query "taskDefinitionArns[0]" --output text)
          echo "TASK_DEF_ARN=$TASK_DEF_ARN" >> $GITHUB_ENV

      - name: Actualizar servicio
        run: |
          aws ecs update-service --cluster test-cluster --service test-svc --task-definition ${{ env.TASK_DEF_ARN }} --force-new-deployment
  
